import type { Metadata } from "next";


import "./globals.css";
import { Inter , Quicksand } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const quicksand = Quicksand({ subsets: ["latin"] })   ;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <div className={inter.className} > </div>

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
   
  );
}
